spring :
  datasource :
    url : jdbc:mysql://localhost:3306/job_connect
    username : developer
    password : secretdevpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate :
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8000

