import companylogo from '../../assets/imgs/companylogo.png'

// const { logo, name, position, jobType, salary, description } = data
export const JobList = [
  {
    jobId: 1,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'ON-SITE',
  },
  {
    jobId: 2,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
  {
    jobId: 3,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'HYBRID',
  },
  {
    jobId: 4,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
  {
    jobId: 5,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
  {
    jobId: 6,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
  {
    jobId: 7,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
  {
    jobId: 8,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
  {
    jobId: 9,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
  {
    jobId: 10,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
  {
    jobId: 11,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
  {
    jobId: 12,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
  {
    jobId: 13,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
  {
    jobId: 14,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
  {
    jobId: 15,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
  {
    jobId: 16,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
  {
    jobId: 17,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
  {
    jobId: 18,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
  {
    jobId: 19,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
  {
    jobId: 20,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
  {
    jobId: 21,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
  {
    jobId: 22,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
  {
    jobId: 23,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
  {
    jobId: 24,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
  {
    jobId: 25,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
  {
    jobId: 26,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
  {
    jobId: 27,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
  {
    jobId: 28,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
  {
    jobId: 29,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
  {
    jobId: 30,
    logo: companylogo,
    position: 'Software Engineer',
    companyName: 'Google, Inc',
    companyAddress: 'Mountain View, California, United States',
    salary: 1200,
    jobType: 'REMOTE',
  },
]